version: '3.8'

services:
  mysql:
    image: mysql:8.0.35-debian
    container_name: mysql-server-biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: nevermore
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: bibliotecario
      MYSQL_PASSWORD: edgarallanpoe
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
